-- 코드를 작성해주세요
SELECT
YEAR(YM) AS YEAR, # YEAR 정수형 표현
# DATE_FORMAT(YM, '%Y') AS YEAR, # DATE_FORMAT 문자열로 표현
ROUND(AVG(PM_VAL1), 2) AS PM10,
ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION1 = '경기도' AND LOCATION2 = '수원'
GROUP BY YEAR   # -- GROUP BY 절 추가 (집계 함수 사용 시 필요)
ORDER BY YEAR ASC;