-- 코드를 입력하세요
SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_OUTS O
    LEFT JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

# ANIMAL_OUTS를 기준으로 LEFT JOIN
# ANIMAL_INS에 매칭되지 않는 레코드 필터링 (I.ANIMAL_ID IS NULL)