-- 코드를 입력하세요
SELECT
I.NAME,
I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;

# LEFT JOIN 사용: ANIMAL_INS를 기준으로 ANIMAL_OUTS와 조인
# WHERE O.ANIMAL_ID IS NULL: 입양 기록이 없는 동물만 필터링
# LIMIT 3: 상위 3마리만 조회

# SELECT 
#     NAME,
#     DATETIME
# FROM ANIMAL_INS
# WHERE ANIMAL_ID NOT IN (
#     SELECT ANIMAL_ID 
#     FROM ANIMAL_OUTS
# )
# ORDER BY DATETIME ASC
# LIMIT 3;