SELECT 
    RH.HISTORY_ID,
    FLOOR(
        C.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) 
        * (100 - IFNULL(DP.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR C 
    ON RH.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    ON C.CAR_TYPE = DP.CAR_TYPE
    AND DP.DURATION_TYPE = (
        CASE 
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 THEN '7일 이상'
        END
    )
ORDER BY FEE DESC, HISTORY_ID DESC;