-- 코드를 입력하세요
SELECT DISTINCT
C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE MONTH(H.START_DATE) = 10 AND C.CAR_TYPE = '세단'
# GROUP BY CAR_ID
ORDER BY C.CAR_ID DESC;

# GROUP BY → DISTINCT로 변경: 중복 제거 목적이라면 DISTINCT가 더 명확하고 간결
# GROUP BY는 집계 함수 없이 사용하면 불필요하게 복잡