-- 코드를 작성해주세요
SELECT
    CASE
        WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
             AND SUM(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) > 0
        THEN 'A'
        WHEN SUM(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) > 0
        THEN 'B'
        WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
        THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE > 0
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC;

# 테스트 케이스 실패
# SELECT DISTINCT
#     CASE
#         WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
#              AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
#         THEN 'A'
#         WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
#         THEN 'B'
#         WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
#         THEN 'C'
#     END AS GRADE,
#     D.ID,
#     D.EMAIL
# FROM DEVELOPERS D
# WHERE D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
#    OR D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
#    OR D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
# ORDER BY GRADE ASC, D.ID ASC;

# 테스트 실패
# SELECT 
#     CASE 
#         WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Front End') 
#              AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
#         THEN 'A'
#         WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
#         THEN 'B'
#         WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Front End')
#         THEN 'C'
#     END AS GRADE,
#     ID,
#     EMAIL
# FROM DEVELOPERS
# HAVING GRADE IS NOT NULL
# ORDER BY GRADE ASC, ID ASC;